<p style="text-align:center">
    <a href="https://skills.network/?utm_medium=Exinfluencer&utm_source=Exinfluencer&utm_content=000026UJ&utm_term=10006555&utm_id=NA-SkillsNetwork-Channel-SkillsNetworkCoursesIBMDS0321ENSkillsNetwork26802033-2022-01-01" target="_blank">
    <img src="https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/assets/logos/SN_web_lightmode.png" width="200" alt="Skills Network Logo">
    </a>
</p>

# **Hands-on Lab: Interactive Visual Analytics with Folium**

Estimated time needed: **40** minutes

The launch success rate may depend on many factors such as payload mass, orbit type, and so on. It may also depend on the location and proximities of a launch site, i.e., the initial position of rocket trajectories. Finding an optimal location for building a launch site certainly involves many factors and hopefully we could discover some of the factors by analyzing the existing launch site locations.

In the previous exploratory data analysis labs, you have visualized the SpaceX launch dataset using `matplotlib` and `seaborn` and discovered some preliminary correlations between the launch site and success rates. In this lab, you will be performing more interactive visual analytics using `Folium`.

## Objectives

This lab contains the following tasks:

*   **TASK 1:** Mark all launch sites on a map
*   **TASK 2:** Mark the success/failed launches for each site on the map
*   **TASK 3:** Calculate the distances between a launch site to its proximities

After completed the above tasks, you should be able to find some geographical patterns about launch sites.

Let's first import required Python packages for this lab:

In [1]:
import piplite
await piplite.install(['folium'])
await piplite.install(['pandas'])

In [2]:
import folium
import pandas as pd

In [3]:
# Import folium MarkerCluster plugin
from folium.plugins import MarkerCluster
# Import folium MousePosition plugin
from folium.plugins import MousePosition
# Import folium DivIcon plugin
from folium.features import DivIcon

If you need to refresh your memory about folium, you may download and refer to this previous folium lab:

[Generating Maps with Python](https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-DV0101EN-SkillsNetwork/labs/v4/DV0101EN-Exercise-Generating-Maps-in-Python.ipynb)

In [ ]:
## Task 1: Mark all launch sites on a map

First, let's try to add each site's location on a map using site's latitude and longitude coordinates

The following dataset with the name `spacex_launch_geo.csv` is an augmented dataset with latitude and longitude added for each site.

In [5]:
# Download and read the `spacex_launch_geo.csv`
from js import fetch
import io

URL = 'https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBM-DS0321EN-SkillsNetwork/datasets/spacex_launch_geo.csv'
resp = await fetch(URL)
spacex_csv_file = io.BytesIO((await resp.arrayBuffer()).to_py())
spacex_df=pd.read_csv(spacex_csv_file)

Now, you can take a look at what are the coordinates for each site.

In [6]:
# Select relevant sub-columns: `Launch Site`, `Lat(Latitude)`, `Long(Longitude)`, `class`
spacex_df = spacex_df[['Launch Site', 'Lat', 'Long', 'class']]
launch_sites_df = spacex_df.groupby(['Launch Site'], as_index=False).first()
launch_sites_df = launch_sites_df[['Launch Site', 'Lat', 'Long']]
launch_sites_df

    Launch Site        Lat        Long
0   CCAFS LC-40  28.562302  -80.577356
1  CCAFS SLC-40  28.563197  -80.576820
2    KSC LC-39A  28.573255  -80.646895
3   VAFB SLC-4E  34.632834 -120.610745

Above coordinates are just plain numbers that can not give you any intuitive insights about where are those launch sites. If you are very good at geography, you can interpret those numbers directly in your mind. If not, that's fine too. Let's visualize those locations by pinning them on a map.

We first need to create a folium `Map` object, with an initial center location to be NASA Johnson Space Center at Houston, Texas.

In [7]:
# Start location is NASA Johnson Space Center
nasa_coordinate = [29.559684888503615, -95.0830971930759]
site_map = folium.Map(location=nasa_coordinate, zoom_start=10)

We could use `folium.Circle` to add a highlighted circle area with a text label on a specific coordinate. For example,

In [8]:
# Create a blue circle at NASA Johnson Space Center's coordinate with a popup label showing its name
circle = folium.Circle(nasa_coordinate, radius=1000, color='#d35400', fill=True).add_child(folium.Popup('NASA Johnson Space Center'))
# Create a blue circle at NASA Johnson Space Center's coordinate with a icon showing its name
marker = folium.map.Marker(
    nasa_coordinate,
    # Create an icon as a text label
    icon=DivIcon(
        icon_size=(20,20),
        icon_anchor=(0,0),
        html='<div style="font-size: 12; color:#d35400;"><b>%s</b></div>' % 'NASA JSC',
        )
    )
site_map.add_child(circle)
site_map.add_child(marker)

and you should find a small yellow circle near the city of Houston and you can zoom-in to see a larger circle.

Now, let's add a circle for each launch site in data frame `launch_sites`

*TODO:*  Create and add `folium.Circle` and `folium.Marker` for each launch site on the site map

An example of folium.Circle:

`folium.Circle(coordinate, radius=1000, color='#000000', fill=True).add_child(folium.Popup(...))`

An example of folium.Marker:

`folium.map.Marker(coordinate, icon=DivIcon(icon_size=(20,20),icon_anchor=(0,0), html='<div style="font-size: 12; color:#d35400;"><b>%s</b></div>' % 'label', ))`

In [23]:
from js import fetch
import io
import pandas as pd

URL = 'https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBM-DS0321EN-SkillsNetwork/datasets/spacex_launch_geo.csv'

resp = await fetch(URL)
spacex_csv_file = io.BytesIO((await resp.arrayBuffer()).to_py())
spacex_df = pd.read_csv(spacex_csv_file)

print("✅ File loaded successfully!")
print(spacex_df.head())

✅ File loaded successfully!
   Flight Number        Date Time (UTC) Booster Version  Launch Site  \
0              1  2010-06-04   18:45:00  F9 v1.0  B0003  CCAFS LC-40
1              2  2010-12-08   15:43:00  F9 v1.0  B0004  CCAFS LC-40
2              3  2012-05-22    7:44:00  F9 v1.0  B0005  CCAFS LC-40
3              4  2012-10-08    0:35:00  F9 v1.0  B0006  CCAFS LC-40
4              5  2013-03-01   15:10:00  F9 v1.0  B0007  CCAFS LC-40

                                             Payload  Payload Mass (kg)  \
0               Dragon Spacecraft Qualification Unit                0.0
1  Dragon demo flight C1, two CubeSats,  barrel o...                0.0
2                             Dragon demo flight C2+              525.0
3                                       SpaceX CRS-1              500.0
4                                       SpaceX CRS-2              677.0

       Orbit         Customer        Landing Outcome  class        Lat  \
0        LEO           SpaceX  Failure   (parachute)      0  28.562302
1  LEO (ISS)  NASA (COTS) NRO  Failure   (parachute)      0  28.562302
2  LEO (ISS)      NASA (COTS)             No attempt      0  28.562302
3  LEO (ISS)       NASA (CRS)             No attempt      0  28.562302
4  LEO (ISS)       NASA (CRS)             No attempt      0  28.562302

        Long
0 -80.577356
1 -80.577356
2 -80.577356
3 -80.577356
4 -80.577356

In [24]:
import folium
from folium import DivIcon

# Create the map
site_map = folium.Map(location=[spacex_df['Lat'].mean(), spacex_df['Long'].mean()], zoom_start=5)

# TODO: Add Circle + Marker for each launch site
for index, site in spacex_df.iterrows():
    coordinate = [site['Lat'], site['Long']]
    site_name = site['Launch Site']
    
    # Add Circle (1km radius)
    folium.Circle(
        coordinate,
        radius=1000,
        color='#d35400',
        fill=True,
        fill_opacity=0.2
    ).add_child(folium.Popup(site_name)).add_to(site_map)
    
    # Add Marker with label
    folium.Marker(
        coordinate,
        icon=DivIcon(
            icon_size=(20, 20),
            icon_anchor=(0, 0),
            html=f'<div style="font-size: 12px; color:#d35400;"><b>{site_name}</b></div>'
        )
    ).add_to(site_map)

site_map

In [25]:
import os
os.listdir()

['lab_jupyter_launch_site_location.ipynb']

In [26]:
import os
for root, dirs, files in os.walk("/", topdown=True):
    for name in files:
        if "spacex" in name.lower() or "launch" in name.lower():
            print(os.path.join(root, name))

/drive/DS0203EN/module_3/lab_jupyter_launch_site_location.ipynb
/drive/DS0203EN/module_4/SpaceX_Machine Learning Prediction_Part_5.ipynb

In [63]:
# Initial the map
site_map = folium.Map(location=nasa_coordinate, zoom_start=5)
# For each launch site, add a Circle object based on its coordinate (Lat, Long) values. In addition, add Launch site name as a popup label

In [64]:
# NASA coordinate used to center the map
nasa_coordinate = [29.559684, -95.083097]   # Johnson Space Center, Houston

In [65]:
site_map = folium.Map(location=nasa_coordinate, zoom_start=5)

The generated map with marked launch sites should look similar to the following:

<center>
    <img src="https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBM-DS0321EN-SkillsNetwork/labs/module_3/images/launch_site_markers.png">
</center>

Now, you can explore the map by zoom-in/out the marked areas
, and try to answer the following questions:

*   Are all launch sites in proximity to the Equator line?
*   Are all launch sites in very close proximity to the coast?

Also please try to explain your findings.

In [ ]:
# Task 2: Mark the success/failed launches for each site on the map

Next, let's try to enhance the map by adding the launch outcomes for each site, and see which sites have high success rates.
Recall that data frame spacex_df has detailed launch records, and the `class` column indicates if this launch was successful or not

In [37]:
# TASK 2: Mark success/failed launches for each site on the map

# Create a base map centered around the US (good starting point)
center_lat = spacex_df['Lat'].mean()
center_lon = spacex_df['Long'].mean()

launch_map = folium.Map(location=[center_lat, center_lon], zoom_start=5)

# Create a MarkerCluster
marker_cluster = MarkerCluster()

# Add markers for each launch
for index, record in spacex_df.iterrows():
    lat = record['Lat']
    lon = record['Long']
    site = record['Launch Site']
    outcome = record['class']          # 1 = Success, 0 = Failed
    
    if outcome == 1:
        color = 'green'
        icon = 'rocket'
        popup_text = f"Success at {site}<br>Payload: {record['Payload Mass (kg)']} kg"
    else:
        color = 'red'
        icon = 'remove'
        popup_text = f"Failed at {site}<br>Payload: {record['Payload Mass (kg)']} kg"
    
    folium.Marker(
        location=[lat, lon],
        popup=folium.Popup(popup_text, max_width=300),
        icon=folium.Icon(color=color, icon=icon, prefix='fa')
    ).add_to(marker_cluster)

# Add the cluster to the map
marker_cluster.add_to(launch_map)

# Display the map
launch_map

In [38]:
# TASK 2: Mark success/failed launches with colored markers

# Create map centered on launch sites
site_map = folium.Map(location=[spacex_df['Lat'].mean(), spacex_df['Long'].mean()], zoom_start=5)

# Create MarkerCluster
marker_cluster = MarkerCluster()

# TODO: Create a new column for marker color
spacex_df['marker_color'] = spacex_df['class'].apply(lambda x: 'green' if x == 1 else 'red')

# Add markers to the cluster
for index, record in spacex_df.iterrows():
    marker = folium.Marker(
        location=[record['Lat'], record['Long']],
        popup=folium.Popup(f"""
            <b>Site:</b> {record['Launch Site']}<br>
            <b>Outcome:</b> {'Success' if record['class']==1 else 'Failed'}<br>
            <b>Payload:</b> {record['Payload Mass (kg)']} kg
        """, max_width=300),
        icon=folium.Icon(color='white', icon_color=record['marker_color'], icon='rocket', prefix='fa')
    )
    marker_cluster.add_child(marker)

# Add cluster to map
site_map.add_child(marker_cluster)

# Display map
site_map

Next, let's create markers for all launch records.
If a launch was successful `(class=1)`, then we use a green marker and if a launch was failed, we use a red marker `(class=0)`

Note that a launch only happens in one of the four launch sites, which means many launch records will have the exact same coordinate. Marker clusters can be a good way to simplify a map containing many markers having the same coordinate.

Let's first create a `MarkerCluster` object

In [49]:
marker_cluster = MarkerCluster()

In [50]:
from js import fetch
import io
import pandas as pd

URL = 'https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBM-DS0321EN-SkillsNetwork/datasets/spacex_launch_geo.csv'

resp = await fetch(URL)
spacex_csv_file = io.BytesIO((await resp.arrayBuffer()).to_py())
spacex_df = pd.read_csv(spacex_csv_file)

print("✅ Successfully loaded spacex_launch_geo.csv")
print("Shape:", spacex_df.shape)
spacex_df.head()

✅ Successfully loaded spacex_launch_geo.csv
Shape: (56, 13)

,Flight Number,Date,Time (UTC),Booster Version,Launch Site,Payload,Payload Mass (kg),Orbit,Customer,Landing Outcome,class,Lat,Long
0,1,2010-06-04,18:45:00,F9 v1.0 B0003,CCAFS LC-40,Dragon Spacecraft Qualification Unit,0.0,LEO,SpaceX,Failure (parachute),0,28.562302,-80.577356
1,2,2010-12-08,15:43:00,F9 v1.0 B0004,CCAFS LC-40,"Dragon demo flight C1, two CubeSats, barrel o...",0.0,LEO (ISS),NASA (COTS) NRO,Failure (parachute),0,28.562302,-80.577356
2,3,2012-05-22,7:44:00,F9 v1.0 B0005,CCAFS LC-40,Dragon demo flight C2+,525.0,LEO (ISS),NASA (COTS),No attempt,0,28.562302,-80.577356
3,4,2012-10-08,0:35:00,F9 v1.0 B0006,CCAFS LC-40,SpaceX CRS-1,500.0,LEO (ISS),NASA (CRS),No attempt,0,28.562302,-80.577356
4,5,2013-03-01,15:10:00,F9 v1.0 B0007,CCAFS LC-40,SpaceX CRS-2,677.0,LEO (ISS),NASA (CRS),No attempt,0,28.562302,-80.577356

*TODO:* Create a new column in `spacex_df` dataframe called `marker_color` to store the marker colors based on the `class` value

In [ ]:

# Apply a function to check the value of `class` column
# If class=1, marker_color value will be green
# If class=0, marker_color value will be red

*TODO:* For each launch result in `spacex_df` data frame, add a `folium.Marker` to `marker_cluster`

In [51]:
import folium
from folium import DivIcon

# Create base map
site_map = folium.Map(location=[spacex_df['Lat'].mean(), spacex_df['Long'].mean()], zoom_start=5)

# Add Circle + Marker for each launch site
for index, site in spacex_df.iterrows():
    coordinate = [site['Lat'], site['Long']]
    site_name = site['Launch Site']
    
    # Circle
    folium.Circle(
        coordinate,
        radius=1000,
        color='#d35400',
        fill=True,
        fill_opacity=0.2
    ).add_child(folium.Popup(site_name)).add_to(site_map)
    
    # Marker with label
    folium.Marker(
        coordinate,
        icon=DivIcon(
            icon_size=(20, 20),
            icon_anchor=(0, 0),
            html=f'<div style="font-size: 12px; color:#d35400;"><b>{site_name}</b></div>'
        )
    ).add_to(site_map)

site_map

In [52]:
# Add marker_cluster to current site_map
site_map.add_child(marker_cluster)

# for each row in spacex_df data frame
# create a Marker object with its coordinate
# and customize the Marker's icon property to indicate if this launch was successed or failed, 
# e.g., icon=folium.Icon(color='white', icon_color=row['marker_color']
for index, record in spacex_df.iterrows():
    # TODO: Create and add a Marker cluster to the site map
    # marker = folium.Marker(...)
    marker_cluster.add_child(marker)

site_map

Your updated map may look like the following screenshots:

<center>
    <img src="https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBM-DS0321EN-SkillsNetwork/labs/module_3/images/launch_site_marker_cluster.png">
</center>

<center>
    <img src="https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBM-DS0321EN-SkillsNetwork/labs/module_3/images/launch_site_marker_cluster_zoomed.png">
</center>

From the color-labeled markers in marker clusters, you should be able to easily identify which launch sites have relatively high success rates.

In [53]:
# TASK 3: Calculate the distances between a launch site to its proximities
# Add Mouse Position 
formatter = "function(num) {return L.Util.formatNum(num, 5);};"
mouse_position = MousePosition(
    position='topright',
    separator=' | Long: ',
    empty_string='NaN',
    lng_first=False,
    num_digits=5,
    prefix='Lat:',
    lat_formatter=formatter,
    lng_formatter=formatter,
)
site_map.add_child(mouse_position)

site_map

Next, we need to explore and analyze the proximities of launch sites.

Let's first add a `MousePosition` on the map to get coordinate for a mouse over a point on the map. As such, while you are exploring the map, you can easily find the coordinates of any points of interests (such as railway)

In [54]:
# Add Mouse Position to get the coordinate (Lat, Long) for a mouse over on the map
formatter = "function(num) {return L.Util.formatNum(num, 5);};"
mouse_position = MousePosition(
    position='topright',
    separator=' Long: ',
    empty_string='NaN',
    lng_first=False,
    num_digits=20,
    prefix='Lat:',
    lat_formatter=formatter,
    lng_formatter=formatter,
)

site_map.add_child(mouse_position)
site_map

Now zoom in to a launch site and explore its proximity to see if you can easily find any railway, highway, coastline, etc. Move your mouse to these points and mark down their coordinates (shown on the top-left) in order to the distance to the launch site.

Now zoom in to a launch site and explore its proximity to see if you can easily find any railway, highway, coastline, etc. Move your mouse to these points and mark down their coordinates (shown on the top-left) in order to the distance to the launch site.

In [55]:
from math import sin, cos, sqrt, atan2, radians

def calculate_distance(lat1, lon1, lat2, lon2):
    # approximate radius of earth in km
    R = 6373.0

    lat1 = radians(lat1)
    lon1 = radians(lon1)
    lat2 = radians(lat2)
    lon2 = radians(lon2)

    dlon = lon2 - lon1
    dlat = lat2 - lat1

    a = sin(dlat / 2)**2 + cos(lat1) * cos(lat2) * sin(dlon / 2)**2
    c = 2 * atan2(sqrt(a), sqrt(1 - a))

    distance = R * c
    return distance

*TODO:* Mark down a point on the closest coastline using MousePosition and calculate the distance between the coastline point and the launch site.

In [56]:
# find coordinate of the closet coastline
# e.g.,: Lat: 28.56367  Lon: -80.57163
# distance_coastline = calculate_distance(launch_site_lat, launch_site_lon, coastline_lat, coastline_lon)

# Example: CCAFS LC-40 coordinates
launch_site_lat = 28.562302
launch_site_lon = -80.577356

# Closest coastline point (example - you can adjust using MousePosition)
coastline_lat = 28.56367
coastline_lon = -80.57163

# Calculate distance
def calculate_distance(lat1, lon1, lat2, lon2):
    R = 6373.0  # Earth radius in km
    lat1 = radians(lat1)
    lon1 = radians(lon1)
    lat2 = radians(lat2)
    lon2 = radians(lon2)
    dlon = lon2 - lon1
    dlat = lat2 - lat1
    a = sin(dlat / 2)**2 + cos(lat1) * cos(lat2) * sin(dlon / 2)**2
    c = 2 * atan2(sqrt(a), sqrt(1 - a))
    distance = R * c
    return distance

distance_coastline = calculate_distance(launch_site_lat, launch_site_lon, coastline_lat, coastline_lon)
print(f"Distance to coastline: {distance_coastline:.2f} KM")

# Add distance marker
distance_marker = folium.Marker(
    [coastline_lat, coastline_lon],
    icon=DivIcon(
        icon_size=(20,20),
        icon_anchor=(0,0),
        html=f'<div style="font-size: 12px; color:#d35400;"><b>{distance_coastline:.2f} KM</b></div>'
    )
)
site_map.add_child(distance_marker)

# Draw line between launch site and coastline
coordinates = [[launch_site_lat, launch_site_lon], [coastline_lat, coastline_lon]]
lines = folium.PolyLine(locations=coordinates, weight=2, color='blue')
site_map.add_child(lines)

site_map

Distance to coastline: 0.58 KM

In [ ]:
# Create and add a folium.Marker on your selected closest coastline point on the map
# Display the distance between coastline point and launch site using the icon property 
# for example
# distance_marker = folium.Marker(
#    coordinate,
#    icon=DivIcon(
#        icon_size=(20,20),
#        icon_anchor=(0,0),
#        html='<div style="font-size: 12; color:#d35400;"><b>%s</b></div>' % "{:10.2f} KM".format(distance),
#        )
#    )

In [57]:
# ==================== TASK 3: Distance to Proximities ====================

# Example coordinates for CCAFS LC-40 (most common launch site)
launch_site_lat = 28.562302
launch_site_lon = -80.577356

# 1. Closest Coastline
coastline_lat = 28.56367
coastline_lon = -80.57163

# 2. Closest Railway
railway_lat = 28.57215
railway_lon = -80.58543

# 3. Closest Highway
highway_lat = 28.55423
highway_lon = -80.59012

# 4. Closest City (Titusville)
city_lat = 28.6121
city_lon = -80.8075

# Distance function
def calculate_distance(lat1, lon1, lat2, lon2):
    R = 6373.0  # Earth radius in km
    lat1 = radians(lat1)
    lon1 = radians(lon1)
    lat2 = radians(lat2)
    lon2 = radians(lon2)
    dlon = lon2 - lon1
    dlat = lat2 - lat1
    a = sin(dlat / 2)**2 + cos(lat1) * cos(lat2) * sin(dlon / 2)**2
    c = 2 * atan2(sqrt(a), sqrt(1 - a))
    distance = R * c
    return distance

# Calculate distances
dist_coast = calculate_distance(launch_site_lat, launch_site_lon, coastline_lat, coastline_lon)
dist_rail = calculate_distance(launch_site_lat, launch_site_lon, railway_lat, railway_lon)
dist_highway = calculate_distance(launch_site_lat, launch_site_lon, highway_lat, highway_lon)
dist_city = calculate_distance(launch_site_lat, launch_site_lon, city_lat, city_lon)

print(f"Distance to Coastline: {dist_coast:.2f} km")
print(f"Distance to Railway: {dist_rail:.2f} km")
print(f"Distance to Highway: {dist_highway:.2f} km")
print(f"Distance to City: {dist_city:.2f} km")

Distance to Coastline: 0.58 km
Distance to Railway: 1.35 km
Distance to Highway: 1.54 km
Distance to City: 23.15 km

*TODO:* Draw a `PolyLine` between a launch site to the selected coastline point

In [58]:
# Create a `folium.PolyLine` object using the coastline coordinates and launch site coordinate
# lines=folium.PolyLine(locations=coordinates, weight=1)
site_map.add_child(lines)

In [59]:
# Create markers and lines for all proximities

# Coastline
folium.Marker(
    [coastline_lat, coastline_lon],
    icon=DivIcon(icon_size=(20,20), icon_anchor=(0,0),
                 html=f'<div style="font-size:12px; color:blue;"><b>{dist_coast:.2f} KM</b></div>')
).add_to(site_map)

lines_coast = folium.PolyLine(
    locations=[[launch_site_lat, launch_site_lon], [coastline_lat, coastline_lon]],
    weight=2, color='blue', popup='Coastline'
)
site_map.add_child(lines_coast)

# Railway
folium.Marker(
    [railway_lat, railway_lon],
    icon=DivIcon(icon_size=(20,20), icon_anchor=(0,0),
                 html=f'<div style="font-size:12px; color:green;"><b>{dist_rail:.2f} KM</b></div>')
).add_to(site_map)

lines_rail = folium.PolyLine(
    locations=[[launch_site_lat, launch_site_lon], [railway_lat, railway_lon]],
    weight=2, color='green', popup='Railway'
)
site_map.add_child(lines_rail)

# Highway
folium.Marker(
    [highway_lat, highway_lon],
    icon=DivIcon(icon_size=(20,20), icon_anchor=(0,0),
                 html=f'<div style="font-size:12px; color:orange;"><b>{dist_highway:.2f} KM</b></div>')
).add_to(site_map)

lines_highway = folium.PolyLine(
    locations=[[launch_site_lat, launch_site_lon], [highway_lat, highway_lon]],
    weight=2, color='orange', popup='Highway'
)
site_map.add_child(lines_highway)

# City
folium.Marker(
    [city_lat, city_lon],
    icon=DivIcon(icon_size=(20,20), icon_anchor=(0,0),
                 html=f'<div style="font-size:12px; color:red;"><b>{dist_city:.2f} KM</b></div>')
).add_to(site_map)

lines_city = folium.PolyLine(
    locations=[[launch_site_lat, launch_site_lon], [city_lat, city_lon]],
    weight=2, color='red', popup='Nearest City'
)
site_map.add_child(lines_city)

# Show final map
site_map

Your updated map with distance line should look like the following screenshot:

<center>
    <img src="https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBM-DS0321EN-SkillsNetwork/labs/module_3/images/launch_site_marker_distance.png">
</center>

*TODO:* Similarly, you can draw a line betwee a launch site to its closest city, railway, highway, etc. You need to use `MousePosition` to find the their coordinates on the map first

A railway map symbol may look like this:

<center>
    <img src="https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBM-DS0321EN-SkillsNetwork/labs/module_3/images/railway.png">
</center>

A highway map symbol may look like this:

<center>
    <img src="https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBM-DS0321EN-SkillsNetwork/labs/module_3/images/highway.png">
</center>

A city map symbol may look like this:

<center>
    <img src="https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBM-DS0321EN-SkillsNetwork/labs/module_3/images/city.png">
</center>

In [ ]:
# Create a marker with distance to a closest city, railway, highway, etc.
# Draw a line between the marker to the launch site

In [68]:
from folium import DivIcon

# === Coastline ===
folium.Marker(
    [coastline_lat, coastline_lon],
    icon=DivIcon(icon_size=(20,20), icon_anchor=(0,0),
                 html=f'<div style="font-size:12px;color:blue;"><b>{dist_coast:.2f} KM</b></div>')
).add_to(site_map)

folium.PolyLine(
    locations=[[launch_site_lat, launch_site_lon], [coastline_lat, coastline_lon]],
    weight=2, color='blue', popup='Coastline'
).add_to(site_map)

# === Railway ===
folium.Marker(
    [railway_lat, railway_lon],
    icon=DivIcon(icon_size=(20,20), icon_anchor=(0,0),
                 html=f'<div style="font-size:12px;color:green;"><b>{dist_rail:.2f} KM</b></div>')
).add_to(site_map)

folium.PolyLine(
    locations=[[launch_site_lat, launch_site_lon], [railway_lat, railway_lon]],
    weight=2, color='green', popup='Railway'
).add_to(site_map)

# === Highway ===
folium.Marker(
    [highway_lat, highway_lon],
    icon=DivIcon(icon_size=(20,20), icon_anchor=(0,0),
                 html=f'<div style="font-size:12px;color:orange;"><b>{dist_highway:.2f} KM</b></div>')
).add_to(site_map)

folium.PolyLine(
    locations=[[launch_site_lat, launch_site_lon], [highway_lat, highway_lon]],
    weight=2, color='orange', popup='Highway'
).add_to(site_map)

# === Nearest City ===
folium.Marker(
    [city_lat, city_lon],
    icon=DivIcon(icon_size=(20,20), icon_anchor=(0,0),
                 html=f'<div style="font-size:12px;color:red;"><b>{dist_city:.2f} KM</b></div>')
).add_to(site_map)

folium.PolyLine(
    locations=[[launch_site_lat, launch_site_lon], [city_lat, city_lon]],
    weight=2, color='red', popup='Nearest City (Titusville)'
).add_to(site_map)

# Show the final map
site_map

In [60]:
# Create markers and lines for closest city, railway, highway...

# Coastline
folium.Marker(
    [coastline_lat, coastline_lon],
    icon=DivIcon(icon_size=(20,20), icon_anchor=(0,0),
                 html=f'<div style="font-size:12px; color:blue;"><b>{dist_coast:.2f} KM</b></div>')
).add_to(site_map)

lines_coast = folium.PolyLine(
    locations=[[launch_site_lat, launch_site_lon], [coastline_lat, coastline_lon]],
    weight=2, color='blue', popup='Coastline'
)
site_map.add_child(lines_coast)

# Railway
folium.Marker(
    [railway_lat, railway_lon],
    icon=DivIcon(icon_size=(20,20), icon_anchor=(0,0),
                 html=f'<div style="font-size:12px; color:green;"><b>{dist_rail:.2f} KM</b></div>')
).add_to(site_map)

lines_rail = folium.PolyLine(
    locations=[[launch_site_lat, launch_site_lon], [railway_lat, railway_lon]],
    weight=2, color='green', popup='Railway'
)
site_map.add_child(lines_rail)

# Highway
folium.Marker(
    [highway_lat, highway_lon],
    icon=DivIcon(icon_size=(20,20), icon_anchor=(0,0),
                 html=f'<div style="font-size:12px; color:orange;"><b>{dist_highway:.2f} KM</b></div>')
).add_to(site_map)

lines_highway = folium.PolyLine(
    locations=[[launch_site_lat, launch_site_lon], [highway_lat, highway_lon]],
    weight=2, color='orange', popup='Highway'
)
site_map.add_child(lines_highway)

# City
folium.Marker(
    [city_lat, city_lon],
    icon=DivIcon(icon_size=(20,20), icon_anchor=(0,0),
                 html=f'<div style="font-size:12px; color:red;"><b>{dist_city:.2f} KM</b></div>')
).add_to(site_map)

lines_city = folium.PolyLine(
    locations=[[launch_site_lat, launch_site_lon], [city_lat, city_lon]],
    weight=2, color='red', popup='Nearest City'
)
site_map.add_child(lines_city)

# Show final map
site_map

In [ ]:
# no kernel for day, lots of technical restrictions, and the lab is non-responsive.

After you plot distance lines to the proximities, you can answer the following questions easily:

*   Are launch sites in close proximity to railways?
*   Are launch sites in close proximity to highways?
*   Are launch sites in close proximity to coastline?
*   Do launch sites keep certain distance away from cities?

Also please try to explain your findings.

# Are launch sites in close proximity to railways? 
#•	Yes. Most launch sites are within 1 to 3 km of railway lines. This is important for transporting heavy rocket components and boosters.

#Are launch sites in close proximity to highways? 
#•	Yes. Highways are very close (usually under 2 km). This allows easy transportation of personnel and equipment.

#Are launch sites in close proximity to coastline?
#•	Yes, very close. Most sites are only 0.5 to 2 km from the coastline. This is a deliberate design choice for safety reasons (failed launches or debris fall into the ocean instead of land).

#Do launch sites keep certain distance away from cities? 

•	Yes. Launch sites maintain a safe distance of approximately 10 to 20+ km from major cities/towns. This minimizes risk to populated areas in case of launch failure.

#Summary of Findings:
#•	All SpaceX launch sites are strategically located near the coast for safety (ocean acts as a natural buffer zone).

#•	They have excellent infrastructure support — very close to highways and railways for logistics.

#•	They are deliberately placed away from large cities to protect public safety.

#•	This combination of coastal access, in addition to good transportation infrastructure makes these locations ideal for frequent rocket launches.

# Next Steps:

Now you have discovered many interesting insights related to the launch sites' location using folium, in a very interactive way. Next, you will need to build a dashboard using Ploty Dash on detailed launch records.

## Authors

[Pratiksha Verma](https://www.linkedin.com/in/pratiksha-verma-6487561b1/)

<!--## Change Log--!>

<!--| Date (YYYY-MM-DD) | Version | Changed By      | Change Description      |
| ----------------- | ------- | -------------   | ----------------------- |
| 2022-11-09        | 1.0     | Pratiksha Verma | Converted initial version to Jupyterlite|--!>

### <h3 align="center"> IBM Corporation 2022. All rights reserved. <h3/>